#pragma config(Sensor, S1,     ,               sensorI2CCustom)
#pragma config(Sensor, S3,     HTIRS2,         sensorI2CCustom)
#pragma config(Motor,  motorA,          ir,            tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "SAAS/drivers/hitechnic-irseeker-v2.h"
#include "Drive.h"

void initializeRobot()
{


  return;
}

task main()
{
  initializeRobot();

  waitForStart(); // Wait for the beginning of autonomous phase.

  nMotorEncoder[ir] = 0;
	nMotorEncoderTarget[ir] = 150;
	motor[ir] = 75;

	while(nMotorRunState[ir] != runStateIdle) {}
	motor[ir] = 0;

	//int offset = getGyroData(S2);
	//if (!writeOffset((long)offset))
	//	return;

	int _dirAC = 0;

	movData mov;

	mov.xComp = 127;
	mov.yComp = 0;
	mov.rot = 0;

	drive(mov, 65, 3400, 0); // forward

	// Read the ir signal
	_dirAC = HTIRS2readACDir(HTIRS2);
	if (_dirAC < 0)
		return; // I2C read error occurred

	//formula: y = 1.4336622452056X^-.42970111468155: X = inner radius: y = rot/xComp
	mov.xComp = 0;
	mov.yComp = 127;
	mov.rot = -35;
	wait1Msec(10);

	if (_dirAC != 4)
		drive(mov, 127); // start orbiting

	while (_dirAC != 4) { //_dirAC != 4
		// Read the ir signal
		drive(mov, 127);
		_dirAC= HTIRS2readACDir(HTIRS2);
		//if (_dirAC < 0)
		//	return; // I2C read error occurred
	}
	drive(mov, 0); //stop orbiting
}
