#pragma config(Sensor, S1,     ,               sensorI2CCustom)
#pragma config(Sensor, S2,     ,               sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "Drive.h"

void initializeRobot()
{
	//initGyro(S2);
}

task main()
{
  initializeRobot();
  //int offset = getGyroData(S2);

  waitForStart(); // Wait for the beginning of autonomous phase.

  movData movAuto;

  movAuto.xComp = 0;
  movAuto.yComp = -127;
  movAuto.rot = 0;

	drive(movAuto, 127);
	wait10Msec(500);

	drive(movAuto, 0);
  /*Servos_SetPosition(S1, 2, 1, 90);
  Servos_SetPosition(S1, 2, 2, 90);

  movAuto.xComp = 50;
  movAuto.yComp = 100;
  movAuto.rot = 15;

  drive(movAuto, 127, 1344000, offset);

  TFileHandle hFileHandle;
	TFileIOResult nIoResult;
	int length = 3;
	string name = "data.txt";
	OpenWrite(hFileHandle, nIoResult, name, length);

	WriteLong(hFileHandle, nIoResult, offset);

	Close(hFileHandle, nIoResult);

	return offset;*/
}
