#pragma config(Sensor, S1,     ,               sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickDriver.c"
#include "Drive.h"

void initializeRobot()
{
  initGyro(S2);
}
task main()
{
  initializeRobot();
  int offset = getGyroData(S2);

  waitForStart();

  movData movAuto;

  movAuto.xComp = 15;
  movAuto.yComp = 127;
  movAuto.rot = 0;

  drive(movAuto, 127, 490000, offset);

  movAuto.xComp = 0;
  movAuto.yComp = 127;
  movAuto.rot = 0;

  drive(movAuto, 63, 56000, offset);

  movAuto.xComp = -1;
  movAuto.yComp = -1;
  movAuto.rot = 0;

  drive(movAuto, 63, 56000, offset);

  TFileHandle hFileHandle;
	TFileIOResult nIoResult;
	int length = 3;
	string name = "data.txt";
	OpenWrite(hFileHandle, nIoResult, name, length);

	WriteLong(hFileHandle, nIoResult, offset);

	Close(hFileHandle, nIoResult);

	return offset;
}
