#pragma config(Sensor, S2,     Bumper,         sensorTouch)
#pragma config(Motor,  motorB,          bump,          tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

void initializeRobot()
{
  return;
}

task main()
{
  initializeRobot();

  waitForStart(); // Wait for the beginning of autonomous phase.

  nMotorEncoder[bump] = 0;
	nMotorEncoderTarget[bump] = 75;
	motor[bump] = 25;

	while(nMotorRunState[bump] != runStateIdle) {}
	motor[bump] = 0;

	while(SensorValue(Bumper) == 0)
	{
	}

	nMotorEncoder[bump] = 0;
	nMotorEncoderTarget[bump] = -75;
	motor[bump] = -25;

	while(nMotorRunState[bump] != runStateIdle) {}
	motor[bump] = 0;

}
