#pragma config(Sensor, S1,     HTIRS2,         sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "SAAS/drivers/hitechnic-irseeker-v2.h"

task main()
{

  waitForStart();

  while (true)
  {
  	int _dirDC = 0;

  	_dirDC = HTIRS2readDCDir(HTIRS2);
		if (_dirDC < 0)
			return; // I2C read error occurred


		nxtDisplayBigTextLine(2, "%d", _dirDC);
		wait10Msec(1);
		nxtDisplayClearTextLine(2);

  }
}
