/* This code was written to test out the lift mechanism */
#pragma config(Sensor, S1,     ,               sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "SAAS/Motors.h"


task main()
{

  waitForStart(); // Wait for the beginning of autonomous phase.


  while (true)
  {
  	Motors_SetSpeed(S1, 1, 1, -34);
  	Motors_SetSpeed(S1, 1, 2, 34);
  	//Motors_SetSpeed(S1, 4, 1, 20);
  }
}
