#pragma config(Sensor, S1,     ,               sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Drive.h"
#include "JoystickDriver.c"
#include "SQRT.h"

task main()
{
    waitForStart();

    byte movX, movY, rot;//movX references the x-axis joystick position, movY references y-axis

    while( true )
    {
        movX = joystick.joy1_x1;
        movY = joystick.joy1_y1-1;
        rot = -1*(joystick.joy1_x2+1);

        if (rot < 10 && rot > 10)
            rot = 0;
        if (movX < 10 && movX > 10)
            movX = 0;
        if (movY < 10 && movY > 10)
            movY = 0;


        int speed = (int)SQRT[movX][movY] + abs(rot));

        if (speed > 127) speed = 127;

        drive( movX, movY, (byte)speed, rot );
    }
}
