#pragma config(Sensor, S1,     ,               sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Drive.h"
#include "JoystickDriver.c"
#include "SQRT.h"
#include "gyro.h"

void initRobot()
{
	initGyro(S2);
}

int findSQRT(int a, int b)
{
	int first = a ? a < b : b;
	int second = b ? a < b : a;

	int answer = 0;

	for (int i = 0; i<first; i++) {
		answer += 129-i;
	}
	answer += second;
	return SQRT[answer];
}

task main()
{
		initRobot();
    waitForStart();

    int curGyro;
    int oldGyro;

    oldGyro = getGyroData(S1);

    byte movX, movY, movX_f, movY_f, rot;	//movX references the x-axis joystick position, movY references y-axis

    while( true )
    {
        movX = joystick.joy1_x1;
        movY = joystick.joy1_y1-1;
        rot = -1*(joystick.joy1_x2+1);

        curGyro = getGyroData(S1);

        if (rot < 10 && rot > -10)
            rot = 0;
        if (movX < 10 && movX > -10)
            movX = 0;
        if (movY < 10 && movY > -10)
            movY = 0;


        if(rot == 0)
        {
        	if(abs(curGyro - oldGyro) > 180)
        		rot = (127/180.0) * abs(curGyro - oldGyro);
        	else
        		rot = -1 * abs(curGyro - oldGyro);
       	}
        else
        	oldGyro = curGyro;

				movX_f = movX * cosDegrees(curGyro) + movY * sinDegrees(curGyro);
				movY_f = movX * -1 * sinDegrees(curGyro) + movY * cosDegrees(curGyro);

        int speed = (int)findSQRT(movX_f, movY_f) + abs(rot);

        if (speed > 127) speed = 127;

        drive( movX_f, movY_f, (byte)speed, rot );
    }
}
